//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLIB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdminUser()
        {
            this.WebNoticeList = new HashSet<WebNoticeList>();
            this.WebNoticeList1 = new HashSet<WebNoticeList>();
            this.PlayerAdminMemo = new HashSet<PlayerAdminMemo>();
        }
    
        public int Id { get; set; }
        public string AdminId { get; set; }
        public string UserPassword { get; set; }
        public string Code { get; set; }
        public short Type { get; set; }
        public short MemberLevel { get; set; }
        public string Title { get; set; }
        public string Name { get; set; }
        public Nullable<int> UpperMemberId { get; set; }
        public long Point { get; set; }
        public float BadugiFreeRate { get; set; }
        public float MatgoFreeRate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateLastLogin { get; set; }
        public string Memo { get; set; }
        public int FriendId { get; set; }
        public bool IsMasterCS { get; set; }
        public long DayPoint { get; set; }
        public long DayPoint2 { get; set; }
        public long PointSettlement { get; set; }
        public bool Deleted { get; set; }
        public long DayBet { get; set; }
        public long DayBet2 { get; set; }
        public int RelayID { get; set; }
        public float HoldemFreeRate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebNoticeList> WebNoticeList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebNoticeList> WebNoticeList1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerAdminMemo> PlayerAdminMemo { get; set; }
    }
}
