//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLIB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventJackpotHunter
    {
        public int id { get; set; }
        public int UserId { get; set; }
        public int e100_50 { get; set; }
        public int e100_100 { get; set; }
        public int e100_200 { get; set; }
        public int e500_50 { get; set; }
        public int e500_100 { get; set; }
        public int e500_200 { get; set; }
        public int e1000_50 { get; set; }
        public int e1000_100 { get; set; }
        public int e1000_200 { get; set; }
        public int e2000_50 { get; set; }
        public int e2000_100 { get; set; }
        public int e2000_200 { get; set; }
        public int e5000_50 { get; set; }
        public int e5000_100 { get; set; }
        public int e5000_200 { get; set; }
        public System.DateTime Date { get; set; }
    }
}
