//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLIB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventLottoResult
    {
        public int Id { get; set; }
        public int EventNumber { get; set; }
        public byte Number1 { get; set; }
        public byte Number2 { get; set; }
        public byte Number3 { get; set; }
        public byte Number4 { get; set; }
        public byte Number5 { get; set; }
        public byte Number6 { get; set; }
        public byte Number7 { get; set; }
        public int Winners { get; set; }
        public long Reward { get; set; }
        public string VideoEmbed { get; set; }
        public System.DateTime DateEnd { get; set; }
        public System.DateTime DateCreate { get; set; }
    }
}
