//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLIB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameRoomList
    {
        public System.Guid Id { get; set; }
        public byte GameId { get; set; }
        public byte ChannelId { get; set; }
        public byte RoomNumber { get; set; }
        public int BetMoney { get; set; }
        public Nullable<int> UserId1 { get; set; }
        public Nullable<long> UserValue1 { get; set; }
        public Nullable<System.DateTime> UserDate1 { get; set; }
        public Nullable<int> UserId2 { get; set; }
        public Nullable<long> UserValue2 { get; set; }
        public Nullable<System.DateTime> UserDate2 { get; set; }
        public Nullable<int> UserId3 { get; set; }
        public Nullable<long> UserValue3 { get; set; }
        public Nullable<System.DateTime> UserDate3 { get; set; }
        public Nullable<int> UserId4 { get; set; }
        public Nullable<long> UserValue4 { get; set; }
        public Nullable<System.DateTime> UserDate4 { get; set; }
        public Nullable<int> UserId5 { get; set; }
        public Nullable<long> UserValue5 { get; set; }
        public Nullable<System.DateTime> UserDate5 { get; set; }
        public Nullable<bool> Restriction { get; set; }
        public Nullable<bool> Restriction2 { get; set; }
        public Nullable<bool> Restriction3 { get; set; }
    }
}
