//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLIB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameBadugiPushBase
    {
        public int Id { get; set; }
        public short Type { get; set; }
        public short Card4 { get; set; }
        public short Card5 { get; set; }
        public short Card6 { get; set; }
        public short Card7 { get; set; }
        public short Card8 { get; set; }
        public short Card9 { get; set; }
        public short Card10 { get; set; }
        public short Card11 { get; set; }
        public short Card12 { get; set; }
        public short Card13 { get; set; }
    }
}
