//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLIB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerMatgoMission
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public byte Mission1 { get; set; }
        public bool Complete1 { get; set; }
        public byte Mission2 { get; set; }
        public bool Complete2 { get; set; }
        public byte Mission3 { get; set; }
        public bool Complete3 { get; set; }
        public byte Mission4 { get; set; }
        public bool Complete4 { get; set; }
        public byte Mission5 { get; set; }
        public bool Complete5 { get; set; }
        public byte Mission6 { get; set; }
        public bool Complete6 { get; set; }
        public byte Mission7 { get; set; }
        public bool Complete7 { get; set; }
        public byte Mission8 { get; set; }
        public bool Complete8 { get; set; }
        public byte Mission9 { get; set; }
        public bool Complete9 { get; set; }
        public byte Mission10 { get; set; }
        public bool Complete10 { get; set; }
    }
}
