//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLIB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Player()
        {
            this.EventLotto = new HashSet<EventLotto>();
            this.EventLottoEnter = new HashSet<EventLottoEnter>();
            this.LogExchangeMileage = new HashSet<LogExchangeMileage>();
            this.LogPlayerNicknameChange = new HashSet<LogPlayerNicknameChange>();
            this.PlayerAdminMemo = new HashSet<PlayerAdminMemo>();
            this.PlayerItemList = new HashSet<PlayerItemList>();
            this.qna = new HashSet<qna>();
            this.PlayerPayment = new HashSet<PlayerPayment>();
            this.LogGamePlayer = new HashSet<LogGamePlayer>();
        }
    
        public int Id { get; set; }
        public System.Guid UserGuid { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public byte MemberLevel { get; set; }
        public string NickName { get; set; }
        public string AdminMemo { get; set; }
        public int FailedLoginAttempts { get; set; }
        public bool Active { get; set; }
        public string FirstIP { get; set; }
        public string LastIP { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public string CreatedFrom { get; set; }
        public Nullable<System.DateTime> LastLoginDateDate { get; set; }
        public Nullable<System.DateTime> LastActivityDate { get; set; }
        public long Point { get; set; }
        public int ShopId { get; set; }
        public float BadugiFreeRate { get; set; }
        public float MatgoFreeRate { get; set; }
        public string Password { get; set; }
        public string MyBoxPassword { get; set; }
        public string PhoneNo { get; set; }
        public bool Quit { get; set; }
        public string QuitReason { get; set; }
        public long DayChangeMoney { get; set; }
        public System.DateTime TryTime { get; set; }
        public string cert_no { get; set; }
        public string ci { get; set; }
        public string di { get; set; }
        public bool IPFree { get; set; }
        public Nullable<int> FriendId { get; set; }
        public bool Online { get; set; }
        public byte Status { get; set; }
        public long TotalGetMoney1 { get; set; }
        public long TotalGetMoney2 { get; set; }
        public long TotalGetMoney3 { get; set; }
        public bool ShopFree { get; set; }
        public bool Old { get; set; }
        public int EventLuckyLottoCount { get; set; }
        public float HoldemFreeRate { get; set; }
        public System.DateTime SelfRestrictedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventLotto> EventLotto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventLottoEnter> EventLottoEnter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogExchangeMileage> LogExchangeMileage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogPlayerNicknameChange> LogPlayerNicknameChange { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerAdminMemo> PlayerAdminMemo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerItemList> PlayerItemList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qna> qna { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerPayment> PlayerPayment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogGamePlayer> LogGamePlayer { get; set; }
    }
}
