//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLIB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductList()
        {
            this.PurchaseList = new HashSet<PurchaseList>();
            this.PlayerItemList = new HashSet<PlayerItemList>();
        }
    
        public int Id { get; set; }
        public string ptype { get; set; }
        public string pname { get; set; }
        public string img { get; set; }
        public Nullable<int> value1 { get; set; }
        public string string1 { get; set; }
        public Nullable<int> value2 { get; set; }
        public string string2 { get; set; }
        public Nullable<int> value3 { get; set; }
        public string string3 { get; set; }
        public Nullable<int> value4 { get; set; }
        public string string4 { get; set; }
        public Nullable<int> value5 { get; set; }
        public string string5 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseList> PurchaseList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerItemList> PlayerItemList { get; set; }
    }
}
