//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLIB
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_AdminList
    {
        public int Id { get; set; }
        public string AdminId { get; set; }
        public short MemberLevel { get; set; }
        public string Title { get; set; }
        public string Name { get; set; }
        public long Point { get; set; }
        public float BadugiFreeRate { get; set; }
        public float MatgoFreeRate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateLastLogin { get; set; }
        public string Memo { get; set; }
        public short Type { get; set; }
        public int MemberCount { get; set; }
        public Nullable<int> UpperMemberId { get; set; }
        public string RegisterCode { get; set; }
        public int ShopCount { get; set; }
        public long MyPoint { get; set; }
        public bool Deleted { get; set; }
        public float HoldemFreeRate { get; set; }
    }
}
