//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLIB
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_FriendList
    {
        public int FriendID { get; set; }
        public string FriendName { get; set; }
        public string UserID { get; set; }
        public string NickName { get; set; }
        public Nullable<int> MatgoWin { get; set; }
        public Nullable<int> MatgoLose { get; set; }
        public Nullable<decimal> MatgoBetMoney { get; set; }
        public Nullable<int> BadugiWin { get; set; }
        public Nullable<int> BadugiLose { get; set; }
        public Nullable<decimal> BadugiBetMoney { get; set; }
        public Nullable<int> play { get; set; }
        public Nullable<decimal> FreeMoney { get; set; }
        public Nullable<decimal> SafeMoney { get; set; }
        public Nullable<int> HoldemWin { get; set; }
        public Nullable<int> HoldemLose { get; set; }
        public Nullable<decimal> HoldemBetMoney { get; set; }
    }
}
