//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLIB
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_LogUserLogin
    {
        public byte GameId { get; set; }
        public int UserId { get; set; }
        public string IP { get; set; }
        public System.DateTime Date { get; set; }
        public string UserName { get; set; }
        public string NickName { get; set; }
        public int ShopId { get; set; }
        public string ShopName { get; set; }
        public string Memo { get; set; }
        public bool Pass { get; set; }
        public string ShopTitle { get; set; }
    }
}
