//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLIB
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_MobileShop
    {
        public string ptype { get; set; }
        public int id { get; set; }
        public string pid { get; set; }
        public int productid { get; set; }
        public string pname { get; set; }
        public string img { get; set; }
        public Nullable<long> paidvalue1 { get; set; }
        public string paidstring1 { get; set; }
        public Nullable<long> paidvalue2 { get; set; }
        public string paidstring2 { get; set; }
        public Nullable<long> paidvalue3 { get; set; }
        public string paidstring3 { get; set; }
        public Nullable<long> paidvalue4 { get; set; }
        public string paidstring4 { get; set; }
        public string purchase_kind { get; set; }
        public int price { get; set; }
        public bool sale { get; set; }
        public Nullable<int> vieworder { get; set; }
        public bool saleweb { get; set; }
    }
}
